# Application Configuration File

####################
# Application Name
####################
# This is the application name. If you log into the manager at
# foobar.manager.markuphive.com and your app lives at
# foobar.app.markuphive.com then your application name is "foobar"

#application_name: foobar

####################
# API Keys
####################
# API keys are required to upload to the markuphive.com hosting platform.
# These are available in your app's manager site's API keys page.

#api_access_key: foo
#api_secret_key: bar


####################
# Routing
####################
# Routes are an array of mappings. The bare minimum of each mapping are the
# "rule" and "script" keys. An optional "data" key should point to the 
# file of the yaml or json data file in the data/ directory. If an array of
# files are given, it will load in sequence and each succeeding file will 
# override any existing keys. You can mix data formats.

#routes:
#  - rule: /
#    template: home.jade
#  - rule: /about-us/
#    template: about-us.jade
#    data: team.yaml
#  - rule: /portfolio/
#    template: portfolio.jade
#    data: [projects.json, clients.yaml]
